version: 2

models:
  - name: customers
    description: A dimension table for customers. One record per customer.
    columns:
      - name: customer_id
        description: Unique ID for each customer
        tests:
          - unique
          - not_null
